In [1]:
import numpy as np
# import random as rd

# 🌟 Exercise 1 : Array Creation and Manipulation
Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 2 : Type Conversion and Array Operations
Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

```python
array([3, 2, 0, 1, 2])
```

In [3]:
list_ = [3.14, 2.17, 0, 1, 2]
arr = np.array(list_)
arr = arr.astype(int)
arr

array([3, 2, 0, 1, 2])

# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

In [4]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:

```python
array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])
```

In [5]:
arr = np.random.rand(4,5)
arr

array([[0.23516104, 0.39213656, 0.51902571, 0.76121312, 0.6154074 ],
       [0.02438073, 0.97590815, 0.6766902 , 0.27764776, 0.67579896],
       [0.39254295, 0.9166596 , 0.46880284, 0.35658064, 0.98646307],
       [0.52049578, 0.98977468, 0.88668157, 0.47577625, 0.90773877]])

# 🌟 Exercise 5 : Indexing Arrays
Instructions

Select the second row from a given 2D NumPy array.

Expected Output:

```python
array([20, 21, 22, 23, 24])
```

In [6]:
arr = np.arange(25).reshape(5,5)
print(arr)

arr1 = arr[1]
print(f"\n## Second row is: {arr1}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

## Second row is: [5 6 7 8 9]


# 🌟 Exercise 6 : Reversing elements
Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:

```python
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
```


In [7]:
arr = np.random.randint(1, 100, 10) # from 1 to 99, 10 random numbers
print(f"## Orginial array is: {arr}")

arr_inv = arr[::-1]
print(f"\n## Reversed array is: {arr_inv} \n")
print("-" * 69)
print("|     NOTE: [::-1] works for all python index-notated sequences     |")
print("-" * 69)

## Orginial array is: [46 48  1 98 90 31 56 24 53 87]

## Reversed array is: [87 53 24 56 31 90 98  1 48 46] 

---------------------------------------------------------------------
|     NOTE: [::-1] works for all python index-notated sequences     |
---------------------------------------------------------------------


# 🌟 Exercise 7 : Identity Matrix
Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:

```python
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
```

In [8]:
arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 🌟 Exercise 8 : Simple Aggregate Funcs
Instructions

Find the sum and average of a given 1D array.

Expected Output:

```python
Sum: 45, Average: 4.5
```

In [9]:
arr = np.random.randint(1, 11, 4)

sum = arr.sum()
avg = arr.mean()

print(f"## the array is: {arr}\n")
print(f"Sum: {sum}, Average: {avg}")

## the array is: [ 8  7 10  8]

Sum: 33, Average: 8.25


# 🌟 Exercise 9 : Create Array and Change its Structure
Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```



In [10]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# 🌟 Exercise 10 : Conditional Selection of Values
Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:

```python
array([1, 3, 5, 7, 9])
```

In [15]:
arr = np.arange(1,26).reshape(5,5)
print(f"## The arrange is:\n\n{arr}")

arr_odd = arr[arr % 2 != 0]
print(f"\n## The odd numbers are: {arr_odd}")

## The arrange is:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

## The odd numbers are: [ 1  3  5  7  9 11 13 15 17 19 21 23 25]
